//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knihovna.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Knihovna.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Knize.
        /// </summary>
        public static string AboutBookLabel {
            get {
                return ResourceManager.GetString("AboutBookLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akce.
        /// </summary>
        public static string ActionHeader {
            get {
                return ResourceManager.GetString("ActionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autora a jeho knihy se nepodařilo smazat.\nDetail: {0}.
        /// </summary>
        public static string AuthorDeleteError {
            get {
                return ResourceManager.GetString("AuthorDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail Autora.
        /// </summary>
        public static string AuthorDetailTitle {
            get {
                return ResourceManager.GetString("AuthorDetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor:.
        /// </summary>
        public static string AuthorLabel {
            get {
                return ResourceManager.GetString("AuthorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor je povinný..
        /// </summary>
        public static string AuthorRequired {
            get {
                return ResourceManager.GetString("AuthorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor byl úspěšně uložen!.
        /// </summary>
        public static string AuthorSavedToast {
            get {
                return ResourceManager.GetString("AuthorSavedToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepodařilo se uložit autora.
        /// </summary>
        public static string AuthorSaveError {
            get {
                return ResourceManager.GetString("AuthorSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoři:.
        /// </summary>
        public static string AuthorsHeader {
            get {
                return ResourceManager.GetString("AuthorsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seznam autorů.
        /// </summary>
        public static string AuthorsListTab {
            get {
                return ResourceManager.GetString("AuthorsListTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum Narození:.
        /// </summary>
        public static string BirthDateLabel {
            get {
                return ResourceManager.GetString("BirthDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knihu se nepodařilo smazat.\nDetail: {0}.
        /// </summary>
        public static string BookDeleteError {
            get {
                return ResourceManager.GetString("BookDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kniha s ISBN &apos;{0}&apos; již existuje..
        /// </summary>
        public static string BookExistsISBN {
            get {
                return ResourceManager.GetString("BookExistsISBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název knihy je povinný..
        /// </summary>
        public static string BookNameRequired {
            get {
                return ResourceManager.GetString("BookNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název knihy je příliš dlouhý, maximální délka je 255 znaků..
        /// </summary>
        public static string BookNameTooLong {
            get {
                return ResourceManager.GetString("BookNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kniha byla úspěšně uložena!.
        /// </summary>
        public static string BookSavedToast {
            get {
                return ResourceManager.GetString("BookSavedToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seznam knih.
        /// </summary>
        public static string BooksListTab {
            get {
                return ResourceManager.GetString("BooksListTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název knihy:.
        /// </summary>
        public static string BookTitleLabel {
            get {
                return ResourceManager.GetString("BookTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrušit.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrušit filtry.
        /// </summary>
        public static string ClearFiltersButton {
            get {
                return ResourceManager.GetString("ClearFiltersButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zavřít.
        /// </summary>
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrzení smazání.
        /// </summary>
        public static string ConfirmAuthorDeleteTitle {
            get {
                return ResourceManager.GetString("ConfirmAuthorDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu chcete smazat autora &apos;{0}&apos;? \n\nVAROVÁNÍ: Tato akce odstraní autora a všechny jeho knihy!.
        /// </summary>
        public static string ConfirmDeleteAuthor {
            get {
                return ResourceManager.GetString("ConfirmDeleteAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat &apos;{0}&apos;?.
        /// </summary>
        public static string ConfirmDeleteBook {
            get {
                return ResourceManager.GetString("ConfirmDeleteBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrzení.
        /// </summary>
        public static string ConfirmDeleteTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kritická chyba databáze.
        /// </summary>
        public static string DatabaseCriticalErrorTitle {
            get {
                return ResourceManager.GetString("DatabaseCriticalErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba při ověřování spojení s databází:\nDetail: {0}.
        /// </summary>
        public static string DbConnectionError {
            get {
                return ResourceManager.GetString("DbConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba databáze.
        /// </summary>
        public static string DBError {
            get {
                return ResourceManager.GetString("DBError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubor s databází nebyl nalezen nebo k němu nelze přistoupit..
        /// </summary>
        public static string DbFileNotFound {
            get {
                return ResourceManager.GetString("DbFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba při mazání.
        /// </summary>
        public static string DeleteErrorTitle {
            get {
                return ResourceManager.GetString("DeleteErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popis:.
        /// </summary>
        public static string DescriptionLabel {
            get {
                return ResourceManager.GetString("DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doplňte povinné údaje zvýrazněné červeně. \n.
        /// </summary>
        public static string FillRequiredData {
            get {
                return ResourceManager.GetString("FillRequiredData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno:.
        /// </summary>
        public static string FirstNameLabel {
            get {
                return ResourceManager.GetString("FirstNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Křestní jméno autora je povinné..
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Křestní jméno může mít maximálně 100 znaků..
        /// </summary>
        public static string FirstNameTooLong {
            get {
                return ResourceManager.GetString("FirstNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN musí obsahovat od 10 do 13 číslic (pomlčky jsou povoleny, ale text ne)..
        /// </summary>
        public static string ISBNError {
            get {
                return ResourceManager.GetString("ISBNError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN:.
        /// </summary>
        public static string ISBNLabel {
            get {
                return ResourceManager.GetString("ISBNLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN je císlo o délce od 10 do 13 císlic pomlcky a mezery jsou povoleny.
        /// </summary>
        public static string ISBNTooltip {
            get {
                return ResourceManager.GetString("ISBNTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jazyk byl změněn. Aby se projevily všechny změny, restartujte prosím aplikaci..
        /// </summary>
        public static string LanguageChangedMessage {
            get {
                return ResourceManager.GetString("LanguageChangedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změna jazyka.
        /// </summary>
        public static string LanguageChangedTitle {
            get {
                return ResourceManager.GetString("LanguageChangedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jazyk:.
        /// </summary>
        public static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jazyk je povinný..
        /// </summary>
        public static string LanguageRequired {
            get {
                return ResourceManager.GetString("LanguageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Príjmení:.
        /// </summary>
        public static string LastNameLabel {
            get {
                return ResourceManager.GetString("LastNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Příjmení autora je povinné..
        /// </summary>
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Příjmení může mít maximálně 100 znaků..
        /// </summary>
        public static string LastNameTooLong {
            get {
                return ResourceManager.GetString("LastNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno:.
        /// </summary>
        public static string NameHeader {
            get {
                return ResourceManager.GetString("NameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Národnost:.
        /// </summary>
        public static string NationalityHeader {
            get {
                return ResourceManager.GetString("NationalityHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Národnost:.
        /// </summary>
        public static string NationalityLabel {
            get {
                return ResourceManager.GetString("NationalityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Národnost je povinná..
        /// </summary>
        public static string NationalityRequired {
            get {
                return ResourceManager.GetString("NationalityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodnota (Value).
        /// </summary>
        public static string Název__Name_ {
            get {
                return ResourceManager.GetString("Název (Name)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nový autor.
        /// </summary>
        public static string NewAuthorButton {
            get {
                return ResourceManager.GetString("NewAuthorButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nová kniha.
        /// </summary>
        public static string NewBookButton {
            get {
                return ResourceManager.GetString("NewBookButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenalezeni žádní autori. Zkuste hledat jinak nebo pridejte nového..
        /// </summary>
        public static string NoAuthorsFound {
            get {
                return ResourceManager.GetString("NoAuthorsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor nemá prírazené žádné knihy..
        /// </summary>
        public static string NoBooksAssigned {
            get {
                return ResourceManager.GetString("NoBooksAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenalezeny žádné knihy. Zkuste upravit filtry nebo pridat novou..
        /// </summary>
        public static string NoBooksFound {
            get {
                return ResourceManager.GetString("NoBooksFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum Vydání:.
        /// </summary>
        public static string PublishDateLabel {
            get {
                return ResourceManager.GetString("PublishDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vydatavatel:.
        /// </summary>
        public static string PublisherLabel {
            get {
                return ResourceManager.GetString("PublisherLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vydavatel je povinný..
        /// </summary>
        public static string PublisherRequired {
            get {
                return ResourceManager.GetString("PublisherRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodnocení:.
        /// </summary>
        public static string RatingHeader {
            get {
                return ResourceManager.GetString("RatingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodnocení:.
        /// </summary>
        public static string RatingLabel {
            get {
                return ResourceManager.GetString("RatingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přečteno:.
        /// </summary>
        public static string ReadHeader {
            get {
                return ResourceManager.GetString("ReadHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přečteno:.
        /// </summary>
        public static string ReadLabel {
            get {
                return ResourceManager.GetString("ReadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadej jméno autora....
        /// </summary>
        public static string SearchAuthorPlaceholder {
            get {
                return ResourceManager.GetString("SearchAuthorPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadej jméno knihy....
        /// </summary>
        public static string SearchBookPlaceholder {
            get {
                return ResourceManager.GetString("SearchBookPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hledat:.
        /// </summary>
        public static string SearchLabel {
            get {
                return ResourceManager.GetString("SearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akce byla úspěšná.
        /// </summary>
        public static string SuccessToast {
            get {
                return ResourceManager.GetString("SuccessToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název:.
        /// </summary>
        public static string TitleHeader {
            get {
                return ResourceManager.GetString("TitleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jejda, v aplikaci došlo k neočekávané chybě. Omlouváme se za komplikace..
        /// </summary>
        public static string UnexpectedErrorMessage {
            get {
                return ResourceManager.GetString("UnexpectedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neočekávaná chyba.
        /// </summary>
        public static string UnexpectedErrorTitle {
            get {
                return ResourceManager.GetString("UnexpectedErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba validace..
        /// </summary>
        public static string ValidationError {
            get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napsané Knihy.
        /// </summary>
        public static string WrittenBooksLabel {
            get {
                return ResourceManager.GetString("WrittenBooksLabel", resourceCulture);
            }
        }
    }
}
