#!/bin/sh
if [ -n "$SKIP_TESTS" ] || [ -n "$NO_TEST" ]; then
  echo "Skipping tests because SKIP_TESTS/NO_TEST is set."
  exit 0
fi

powershell -ExecutionPolicy Bypass -File "app/knihovna/.githooks/pre-commit.ps1"
exit $? 
