name: .NET Core Desktop Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore dependencies
      run: dotnet restore ./app/Knihovna

    - name: Build
      run: dotnet build ./app/Knihovna --configuration Release --no-restore

    - name: Test
      run: dotnet test ./app/Knihovna --configuration Release --no-build

    - name: Publish
      run: dotnet publish ./app/Knihovna --configuration Release --no-build -o ./artifacts/publish

    - name: Upload publish artifact
      uses: actions/upload-artifact@v4
      with:
        name: Knihovna
        path: ./artifacts/publish
